name: "CI"

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.10']
        node-version: [14.x]
    env:
      SERVER: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."https://git@".insteadOf git://
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Start Services
        run: ./scripts/ci-start-services.sh
      - name: Pytest
        run: pytest --log-level=ERROR --disable-warnings
      - name: Behave
        working-directory: ./server
        run: behave --format progress2 --logging-level=ERROR

  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CLIENT: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."https://git@".insteadOf git://
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run hint
      - name: Unit Tests
        run: npm run unit_test
