name: "CI"

on: [push, pull_request]

jobs:
  server:
    runs-on: ubuntu-latest
    services:
      redis:
          image: redis:alpine
          ports:
              - "6379:6379"

      mongo:
          image: mongo:4.4
          ports:
              - "27017:27017"

      elastic:
          image: elasticsearch:7.17.23
          ports:
              - "9200:9200"
          env:
            discovery.type: single-node

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        node-version: ['14', '20']
    env:
      SERVER: true
      OPENSSL_CONF: /dev/null  # fixes phantomjs error
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'server/requirements.txt'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: git config --global url."https://git@".insteadOf git://
      - name: Setup Environment
        run: ./scripts/ci-install.sh
      - name: Pytest
        run: pytest --log-level=ERROR --disable-warnings
      - name: Behave
        working-directory: ./server
        run: behave --format progress2 --logging-level=ERROR

  client:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['14', '20']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git config --global url."https://git@".insteadOf git://
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run hint
      - name: Unit Tests
        run: npm run unit_test
